### ISSUE TITLE
Only finds tabs that are not collapsed

### ISSUE THREAD

**Issue by mzso** [NiklasGollenstede/tst-search#11]
Hi!

I think this issue largely defeats the purpose of search if you have a larger number of tabs, many of them collpased. It would mean you need to go through all of them and open un-collapse every sub-branch, before you can start searching.

**Comment by NiklasGollenstede** [comment]
Well, kind of. They were actually always "found" by the search, one just couldn't (directly) see them as they were still collapsed.
If that is set in the options, the search will now expand the branches that contain the active search result.
I'll assume for now that that addressed this issue.
