### ISSUE TITLE
TST subpanel does not work with Nightly 106.0a1

### ISSUE THREAD

**Issue by piroor** [NiklasGollenstede/tst-search#25]
Maybe due to https://bugzilla.mozilla.org/show_bug.cgi?id=1773115 now addons require to give permission to load its resources from outside including both websites and other addons, otherwise TST just show blank subpanel.

I hope [the patch for TST Bookmarks Subpanel](https://github.com/piroor/tst-bookmarks-subpanel/commit/5f5e0fc71553c6dce251a1e3fd1ff3c0cf7fbed9) which also provide subpanel contents to TST helps you to fix this on this project.

**Comment by NiklasGollenstede** [comment]
Yeap, thanks for filing!

I don't think the linked FF bug is very related, though it is nice to see that they came up with a much more granular [`web_accessible_resources` for manifest version 3](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/web_accessible_resources#manifest_v3_syntax).

I hope I will get to fixing this and addressing https://github.com/piroor/treestyletab/issues/3171 in the coming days ...
