### ISSUE TITLE
Close buttons are indented on child tabs

### ISSUE THREAD

**Issue by durka** [NiklasGollenstede/tst-search#29]
With this extension installed, tabs that aren't at the root of the tree have their close buttons moved to the right. For tabs that are two or more levels deep, the close button is further right than the sidebar with so it can't be clicked. Resizing the sidebar doesn't help because the close buttons move as well.

Clean profile with only TST installed:

![image](https://github.com/NiklasGollenstede/tst-search/assets/47007/12d93804-c7be-41cb-b555-44e2e185013b)

After installing TST Tab Search:

![image](https://github.com/NiklasGollenstede/tst-search/assets/47007/c3a98037-1621-4e8d-a38c-816089e1bd51)

**Comment by NiklasGollenstede** [comment]
Huh. There has to be something else at play here as well. I just circled through all of TST's themes (yours looks like Photon) and none of them have (or to my knowledge ever had) this display error (with TST Search installed).

I don't really have any idea what would be causing this, but/so without further insight, I also have no idea how to address this ...

**Comment by durka** [comment]
I wish there was! But the screenshots I showed are from a completely blank
profile, besides the two extensions, so that should remove all the
variables. Are you not able to reproduce?

Screenshots are from Ubuntu 22.04 but I tried it on macOS as well and the
same thing happened.

**Comment by dstd** [comment]
Same here. Not sure when this issue appeared, but after 1 month of vacation I found that the close button is hidden on some tabs

**Comment by dstd** [comment]
> @NiklasGollenstede 
> Huh. There has to be something else at play here as well. I just circled through all of TST's themes (yours looks like Photon) and none of them have (or to my knowledge ever had) this display error (with TST Search installed).

My steps to reproduce:
1. Open new window, with tab#1
2. Go to https://www.google.com/search?q=zzzzz+zzzzz+zzzzz+zzzzz+zzzzz+zzzzz+zzzzz+zzzzz
3. Open tab#2
4. Go to https://www.google.com/search?q=zzzzz+zzzzz+zzzzz+zzzzz+zzzzz+zzzzz+zzzzz+zzzzz
5. Drag and drop tab#2 as a child of tab#1
6. Now tab#2 has the close button missed (out of the view box), while tab#1 has it visible

To make it more reproducible shrink the width of the sidebar to the minimum.

**Comment by piroor** [comment]
I removed `overflow:hidden` for some elements at TST 3.9.16 to avoid unexpected cropping of box-shadow. It looks that the change causes this problem.
https://github.com/piroor/treestyletab/commit/cb6e6855511e616d28625445869a0a0b4c25587a

**Comment by NiklasGollenstede** [comment]
Yes, thanks all. I now have the problem as well (for some reason, both my laptops only received the TST update today, after 6 days or so).

A now-missing `overflow:hidden` could indeed be the cause of this. I looked at the problem earlier and think there should be a different workaround (than just adding the `overflow:hidden` again).
Now I am on the right computer, let me see whether I still remember how to do web-extension stuff ...

**Comment by NiklasGollenstede** [comment]
Ok. The problem was caused by the previous implementation of the (probably largely unused) feature to show tab ids while searching (to allow quick jumping to tabs with the keyboard).
The IDs are in a different (IMO better) position now, and the implementation (CSS) is much, much simpler.

@piroor I noticed that under certain conditions, the `.label-content` gets a `data-tab-id="null". The ID is correct on the parent elements. I observed this on tabs that are (re-)opened after TST (or the sidebar?) was loaded, and on all tabs when the sidebar is reloaded:
![image](https://github.com/NiklasGollenstede/tst-search/assets/10552031/58c5eb6d-ae7e-4bd5-ba27-a0fffdd986a7)

The fix is in the dev build now. I will probably make a proper release tomorrow.

**Comment by piroor** [comment]
@NiklasGollenstede Hmm, I couldn't reproduce the `data-tab-id="null"` problem on my environment whether TST Tab Search is installed or not.

https://github.com/piroor/treestyletab/blob/22e96f78776c7dce2d447881a014c698e2f872f6/webextensions/sidebar/components/TabLabelElement.js#L121
https://github.com/piroor/treestyletab/blob/22e96f78776c7dce2d447881a014c698e2f872f6/webextensions/sidebar/components/TabElement.js#L260

The `data-tab-id` of `.label-content` is applied when the element is initialized, and the value is from `tab-item` and `tab-label` elements. Could you confirm that the `tab-item` and `tab-label` have valid `data-tab-id` value on your case?

**Comment by Mike6547** [comment]
Has FIX already been published on the Master branch?

**Comment by NiklasGollenstede** [comment]
@piroor Yes, the parent elements have the correct IDs, it's only `null` on the `.label-content`:

![image](https://github.com/NiklasGollenstede/tst-search/assets/10552031/c1e2d50a-eb57-42cb-9644-5cbafbda238a)

**Comment by NiklasGollenstede** [comment]
I uploaded v0.0.7 on AMO, the fix is now published!

**Comment by durka** [comment]
I can confirm the fix! After the extension updated automatically, I had to go to the preferences and re-register it with TST for it to show up in the sidebar. Thanks for the quick fix!
