### ISSUE TITLE
Dark color theme

### ISSUE THREAD

**Issue by kristofferR** [NiklasGollenstede/tst-search#3]
Thanks again for the extension, awesome job. 

However, I'm not a fan of the current colors, doesn't match my theme. It would be cool if you added an option to change themes to a darker one.

<img width="842" alt="Skjermbilde 2021-04-26 kl  18 19 51" src="https://user-images.githubusercontent.com/481270/116116953-03a2de80-a6bc-11eb-9356-bf4fd0d3434d.png">

**Comment by kristofferR** [comment]
I just noticed that your screenshot is actually dark, not sure what's going on there.

**Comment by NiklasGollenstede** [comment]
It currently uses the CSS `@media (prefers-color-scheme: dark)` query to apply the dark colors.
I am not entirely sure where Firefox gets that preference from (I think it is the OS setting, e.g. in Windows whether you use dark window colors, on Linux somehow deduced from the system color scheme).

I'll think about how to add an option to force the dark theme. Or @piroor , is there a way to know the color scheme (or a set of CSS color `var`s) selected by the user in TST itself?
Later though, got to run now ...

**Comment by kristofferR** [comment]
I'm using the color scheme "Photon" under TST Development options too, just noticed that that's a seperate option from the TST theme, if that proves helpful.

**Comment by NiklasGollenstede** [comment]
I _think_ the theme you select for Firefox does not matter for this (and the one for TST certainly doesn't). This color preference is pulled from the system (and may also change, e.g. based on the time of day).
You can overwrite it in Firefox, though: https://stackoverflow.com/a/56757527

Anyway, in addition to the automatically updating theme selection, you can now also fix the light or dark theme in TST Tab Search. Just ask Firefox to "check for updates", and the option should show up.

**Comment by kristofferR** [comment]
Thanks for that option, looks great now!

I don't think the system color preference should matter at all for how the TST search look though, lots of people use a dark theme with Light Mode, and prefer white web pages at the same time.

It would be much better and cleaner to grab the Firefox theme colors, like TST is doing to style it's UI.

That way it would look great automatically even with weird themes, like [Pink Pink Pink Pink Pink](https://addons.mozilla.org/en-US/firefox/addon/pink-pink-pink-pink-pink/.

**Comment by NiklasGollenstede** [comment]
Yeah, you are right. Taking Firefox's theme colors would be better, but would also be considerably more effort than the initial `@media (prefers-color-scheme: dark)` was.
Should I ever have another reason to familiarize myself with those APIs (which I haven't worked with yet), then I will maybe also implement this here. For now two simple theme options with some sort of auto-detection has to do.

**Comment by piroor** [comment]
I'm negative to add features to apply TST's theme to subpanels, because it will make things more chaotic.

* system color
* Firefox's theme color
* dark mode

There are already three factors around UI styling, and adding one more factor "TST's theme color" will make it more harder to control colors by authors of subpanels...

Thus I think that the color scheme of a subpanel should be managed by the subpanel provider addon itself. Indeed a reference addon of the subpanel API https://github.com/piroor/tst-bookmarks-subpanel just supports the system Dark theme for now and needs to more commits for a better integration with Firefox theme.

**Comment by NiklasGollenstede** [comment]
I think something in that regard could be done without creating too much of a mess, but it may indeed not be worth the implementation effort. Certainly not for an UI element as small as this.
Thanks for your answer, @piroor!
