### ISSUE TITLE
Escape key (Esc) only clear search in the panel of TST, not in the panel spawned through Firefox toolbar

### ISSUE THREAD

**Issue by DivineMK** [NiklasGollenstede/tst-search#32]
Escape key clear search in this panel:
![image](https://github.com/NiklasGollenstede/tst-search/assets/42614396/f3ac6bb4-3ba0-4920-adab-001e323db256)

But it only close this panel and doesn't clear the search, making the tab still opaque:

https://github.com/NiklasGollenstede/tst-search/assets/42614396/f3611a70-dffc-4f3b-a161-573f4392a8cd

**Comment by NiklasGollenstede** [comment]
Yes. This is a [known limitation of Firefox](https://github.com/NiklasGollenstede/tst-search/blob/master/src/common/options.esm.js#L147C5-L150C249):

> *Focus Search Bar Hotkey*
> Browser-wide hotkey to focus the the search bar.
> NOTE: Firefox currently does not allow extensions to focus (elements in) their sidebars (see <a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1502713">Firefox bug 1502713</a>). So for now, this extension instead opens a small panel at the top of the window with a copy of the search bar. For this to work, the extension's icon <b>has to be in the browser navigation bar</b>.
> Since <code>Esc</code> keypresses are also unavailable while a panel is open, pressing this hotkey again, while the panel has focus, clears the search. Quickly double pressing the hotkey at any time also clears the search, and closes the panel

I.e. to clear the search in the panel, double-press/re-press the shortcut that opens/opened it.

There is, unfortunately, nothing else I can do about that.

**Comment by DivineMK** [comment]
The double pressing hotkey feature is even better than ESC!  I totally missed that. Is it possible for you to make it clearer in the extension description in case others miss this cool feature?

**Comment by NiklasGollenstede** [comment]
You *did* know that the shortcut exists, so I assume you looked at that part of the settings (or how did you get to know about it?).
The quote above is the description of the shortcut on the settings page. That seems like an appropriate place to describe this situation. Do you have a different idea?

**Comment by DivineMK** [comment]
Yes I did read that description but I didn't know what the hotkey in the description refer to. I propose changing the description to this:
Since Esc keypresses are also unavailable while a panel is open, pressing this hotkey _**(default Ctrl+Shift+T)**_ again, while the panel has focus, clears the search. Quickly double pressing the hotkey at any time also clears the search, and closes the panel.
