### ISSUE TITLE
TST Search showing ?? as result; 'tab.favIconUrl is undefined'

### ISSUE THREAD

**Issue by DoTrONoL** [NiklasGollenstede/tst-search#39]
Suddenly this happened when I tried to search. I did not install any extensions, nor I do know if the main plugin updated itself.

I'm currently using Firefox 132.0.1 (64-bit)

![image](https://github.com/user-attachments/assets/f933d836-105c-4dcc-a7ff-513d7a50f07f)

![image](https://github.com/user-attachments/assets/f1ba44e3-5d97-4f51-82d0-149119a1c321)

**Comment by klassixx** [comment]
I'm also experiencing this, just noticed this morning. Firefox on both windows and mac.

**Comment by sodala33** [comment]
Got the same problem here with FF 132.0.2 (Win 10). It started a few days ago. It seems to be connected with certain websites. I experimented with dragging whole tab trees into new windows: sometimes TST works, sometimes the error message pops up. But I wasn't able to pin down the problematic sites.

**Comment by droopy4096** [comment]
here's where the bug comes from: https://github.com/NiklasGollenstede/tst-search/blob/2d543fbcc877778d32135562677d92e680cc5c3b/src/background/index.esm.js#L274 (well, not much granularity here). But extracted this from the Debug:

![Screenshot_20241114_070841](https://github.com/user-attachments/assets/7b7d4e7c-a6db-401b-83f0-3bf1d759dcab)

**Comment by sodala33** [comment]
Okay, cool, thank you ... what do we do next? 😅

**Comment by DoTrONoL** [comment]
@sodala33 We do sit down and cry. Or someone could try to solve this issue by sending a PR, or maybe @piroor could help us since I saw him helping in other threads, as Niklas hasn't maintained this plugin for a while. 🙏

**Comment by sodala33** [comment]
Sorry for being an absolute Github n00b, @DoTrONoL, but I think a PR (if that means "pull request") sounds like the best option. However that works 🙈

**Comment by DoTrONoL** [comment]
Guys, it's working for me again in newer Firefox's version: 133+
