### ISSUE TITLE
Add option to hide advanced search icons

### ISSUE THREAD

**Issue by kristofferR** [NiklasGollenstede/tst-search#4]
Would love it if you could add an option to hide the three advanced search option icons in the search box, they're not neccesary in my use case. :)

**Comment by NiklasGollenstede** [comment]
I have to admit this hurts a bit, but you will not be the only user to whom these buttons will mostly be visual clutter.
I will keep them by default, but you can hide them now.

**Comment by mzso** [comment]
[**@NiklasGollenstede**](https://github.com/NiklasGollenstede) commented on [2021. ápr. 27. 14:42 CEST](https://github.com/NiklasGollenstede/tst-search/issues/4#issuecomment-827576258 "2021-04-27T12:42:28Z - Replied by Github Reply Comments"):
> I have to admit this hurts a bit, but you will not be the only user to whom these buttons will mostly be visual clutter.  
> I will keep them by default, but you can hide them now.

I don't mind them there. But to be honest I don't see myself doing too many sophisticated searches for tab titles/urls that would require them.
