### ISSUE TITLE
[Feature Request] Add entry `Show all tabs` while filter is active

### ISSUE THREAD

**Issue by sakkamade** [NiklasGollenstede/tst-search#7]
Upon finishing the search task and wishing to discard the active filter,
 it would be much easier to click sticky entry `Show All Tabs...` right under all the filtered tabs than tiny `x` button, 
still more so if there are only few tabs have been founded. (I use, of course, `Other/Misses` -> `Hide Completely`.)

The behaviour is present, and used to be exceedingly handy to me in _Tab Center Redux_.

**Comment by NiklasGollenstede** [comment]
So, if I get that correctly, you want a last item in the tab list that says `Show All Tabs`, which is only available/visible when a search is active, and then clears that search when clicked?

That won't (with TST's current APIs). TST Search can only add content to the fixed size area at the bottom (or in principle to individual tabs).

What you can do though to clear the search, without needing to click the small `x`, is press `esc` on the keyboard (while having focus on the search bar).

**Comment by sakkamade** [comment]
> So ... when clicked?

Yes.

> That won't (with TST's current APIs).

I see.
> press esc on the keyboard 

Indeed; but then I need to click search field, since I will most likely click on some tab after search operation,
 and only after that press Esc...

Thank you.

**Comment by NiklasGollenstede** [comment]
For what it's worth: you can now (moderately quickly) double tab `Ctrl`+`Shift`+`F` (or whatever you customized that to) to clear the search and close the search popup (which will briefly open).
