### ISSUE TITLE
Text focus using shortcuts

### ISSUE THREAD

**Issue by haoadoresorange** [NiklasGollenstede/tst-search#9]
Hello,

I'm not sure if this is a bug or expected behavior.
When using the keyboard shortcut, I see the panel search open but the cursor isn't focus on it, so I can't type to the search bar.

**Comment by NiklasGollenstede** [comment]
You mean the "Focus Search Bar Hotkey" (default: `Ctrl + Shift + F`)?
The entire point of that is that you can type straight away, without moving your mouse/cursor.
So the panel should get focus, and in any setup I have tried it so far, it does (FF 88 / 89 beta, Linux / Windows, normal and with the button in the "more tools .." menu).

Can you provide more details?

**Comment by haoadoresorange** [comment]
I'm on Windows, FF88.
Even when I click on the button/icon in the toolbar, it stills only open the panel without cursor focus.

**Comment by haoadoresorange** [comment]
On debug I have this
![image](https://user-images.githubusercontent.com/22086462/120123002-0e113600-c19c-11eb-8286-943d9e77a451.png)
But seems not related to the problem.

**Comment by NiklasGollenstede** [comment]
Yeah, I don't think that error message is related ...

I have fairly little else to go on, though. I have just tested FF88 on Windows again. It woks there ...

Best I can do is ask you to troubleshoot for now: `Win`+`R` > `firefox -P` > `Create profile ...`, continue ... > select new profile, uncheck the auto selection, Start > install TST Tab Search (actually no need fot TST itself) > `Ctrl + Shift + F` > :shrug:

**Comment by haoadoresorange** [comment]
So I figured it out.
It doesn't work if the icon is in the overflow menu while having other extensions.
It works when being in the overflow menu if it is the ONLY extension that is enabled.

**Comment by NiklasGollenstede** [comment]
:roll_eyes: Well. That is pretty clearly out of the hands of the extension itself. I did indeed not test that scenario, good on you to find this one out ^^

You know how to avoid the issue now, but you could still file a bug report with Firefox itself (even with the significant "proton" UI changes in FF89 this still happens).

**Comment by haoadoresorange** [comment]
OK ! I will file a bug report with them then ! close this issue here.

**Comment by haoadoresorange** [comment]
Thanks for you comments !
